;;; drepl-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from drepl.el

(register-definition-prefixes "drepl" '("drepl-"))


;;; Generated autoloads from drepl-ipython.el

 (autoload 'drepl-ipython "drepl-ipython" nil t)
(register-definition-prefixes "drepl-ipython" '("drepl-ipython-"))


;;; Generated autoloads from drepl-lua.el

 (autoload 'drepl-lua "drepl-lua" nil t)
(register-definition-prefixes "drepl-lua" '("drepl-lua-"))


;;; Generated autoloads from drepl-node.el

 (autoload 'drepl-node "drepl-node" nil t)
(register-definition-prefixes "drepl-node" '("drepl-node-"))


;;; Generated autoloads from drepl-usql.el

 (autoload 'drepl-usql "drepl-usql" nil t)
(register-definition-prefixes "drepl-usql" '("drepl-usql-"))

;;; End of scraped data

(provide 'drepl-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; drepl-autoloads.el ends here
